project_id = "vyyyunltcxwqafdhytxs"

[functions.agenda-disponibilidade]
verify_jwt = false

[functions.agenda-disponibilidade-categoria]
verify_jwt = false

[functions.agenda-reservar]
verify_jwt = false

[functions.chat-atendimento]
verify_jwt = false
