project_id = "vyyyunltcxwqafdhytxs"

[functions.agenda-disponibilidade]
verify_jwt = false

[functions.agenda-disponibilidade-categoria]
verify_jwt = false

[functions.agenda-reservar]
verify_jwt = false

[functions.agenda-reservar-multiplos]
verify_jwt = false

[functions.chat-atendimento]
verify_jwt = false

[functions.listar-usuarios]
verify_jwt = false

[functions.zapi-status]
verify_jwt = false

[functions.zapi-webhook]
verify_jwt = false
